---
title: "Zinc supplementation on Prediabetes"
author: "Kadek Adit Wiryadana"
date: "`r Sys.time()`"
output:
  pdf_document: default
  html_document: 
    code_folding: hide
---

## Preparation
### Load package
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(meta)
library(googlesheets4)
```


### Import Data

#### Import data & save locally
```{r eval=FALSE, include=FALSE}
data <- read_sheet("https://docs.google.com/spreadsheets/d/1W4YqKc7r_4rf47tSD635Ztq8n4g3srQdw6eaFJYKi70/edit#gid=0")
write_csv(data, "data.csv")

```

#### Import data from local storage
```{r message=FALSE, warning=FALSE}
data <- read_csv("data.csv")
#attach(data)
```

### Analysis

#### Metanalysis Fasting Plasma Glucose

```{r fpg, fig.align='center', fig.width=12, fig.height=4}
fpg <- metacont(n.e = total_zinc,
                mean.e = mean_fpg_zinc,
                sd.e = sd_fpg_zinc,
                n.c = total_placebo,
                mean.c = mean_fpg_placebo,
                sd.c = sd_fpg_placebo,
                data = data,
                studlab = paste0(author,", ",year))
print(summary(fpg), digits = 2)

meta::forest(fpg,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-15,15))
```

#### Metanalysis Insulin Sensitivity Index

```{r insens, fig.align='center', fig.width=12, fig.height=4}
insens <- metacont(n.e = total_zinc,
                mean.e = mean_InSens_zinc,
                sd.e = sd_InSens_zinc,
                n.c = total_placebo,
                mean.c = mean_InSens_placebo,
                sd.c = sd_InSens_placebo,
                data = data[-2,],
                studlab = paste0(author,", ",year))
print(summary(insens), digits = 2)

meta::forest(insens,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-30,30)
             )
```

#### Metanalysis Insulin Resistance Index

```{r inres, fig.align='center', fig.width=12, fig.height=4}
inres <- metacont(n.e = total_zinc,
                mean.e = mean_InRes_zinc,
                sd.e = sd_InRes_zinc,
                n.c = total_placebo,
                mean.c = mean_InRes_placebo,
                sd.c = sd_InRes_placebo,
                data = data,
                studlab = paste0(author,", ",year))
print(summary(inres), digits = 2)

meta::forest(inres,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-1,1)
             )
```

#### Metanalysis Beta Cell Function

```{r betafunc, fig.align='center', fig.width=12, fig.height=4}
beta <- metacont(n.e = total_zinc,
                mean.e = mean_BetaFunc_zinc,
                sd.e = sd_BetaFunc_zinc,
                n.c = total_placebo,
                mean.c = mean_BetaFunc_placebo,
                sd.c = sd_BetaFunc_placebo,
                data = data,
                studlab = paste0(author,", ",year))
print(summary(beta), digits = 2)

meta::forest(beta,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-40,40)
             )
```

#### Metanalysis Triglyceride

```{r tg, fig.align='center', fig.width=12, fig.height=4}
tg <- metacont(n.e = total_zinc,
                mean.e = mean_TG_zinc,
                sd.e = sd_TG_zinc,
                n.c = total_placebo,
                mean.c = mean_TG_placebo,
                sd.c = sd_TG_placebo,
                data = data[-3,],
                studlab = paste0(author,", ",year))
print(summary(tg), digits = 2)

meta::forest(tg,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-100,100)
             )
```

#### Metanalysis HDL

```{r hdl, fig.align='center', fig.width=12, fig.height=4}
hdl <- metacont(n.e = total_zinc,
                mean.e = mean_HDL_zinc,
                sd.e = sd_HDL_zinc,
                n.c = total_placebo,
                mean.c = mean_HDL_placebo,
                sd.c = sd_HDL_placebo,
                data = data[-3,],
                studlab = paste0(author,", ",year))
print(summary(hdl), digits = 2)

meta::forest(hdl,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-15,15)
             )
```

#### Metanalysis LDL

```{r ldl, fig.align='center', fig.width=12, fig.height=4}
ldl <- metacont(n.e = total_zinc,
                mean.e = mean_LDL_zinc,
                sd.e = sd_LDL_zinc,
                n.c = total_placebo,
                mean.c = mean_LDL_placebo,
                sd.c = sd_LDL_placebo,
                data = data[-3,],
                studlab = paste0(author,", ",year))
print(summary(ldl), digits = 2)

meta::forest(ldl,
             digits = 2,
             #sortvar = year,
             label.e = "Zinc",
             label.c = "Placebo",
             xlim = c(-40,40)
             )
```


```{bash}
cp zinc_prediabetes.html index.html
```

